// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: third_party/companion_protos/messageV1.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Com_Google_Companionprotos_MessageV1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var version: Int32 = 0

  public var operation: Com_Google_Companionprotos_OperationType = .unknown

  public var packetNumber: UInt32 = 0

  public var totalPackets: UInt32 = 0

  public var isPayloadEncrypted: Bool = false

  public var payload: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "com.google.companionprotos"

extension Com_Google_Companionprotos_MessageV1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MessageV1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "version"),
    2: .same(proto: "operation"),
    3: .standard(proto: "packet_number"),
    4: .standard(proto: "total_packets"),
    5: .standard(proto: "is_payload_encrypted"),
    6: .same(proto: "payload"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.version) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.operation) }()
      case 3: try { try decoder.decodeSingularFixed32Field(value: &self.packetNumber) }()
      case 4: try { try decoder.decodeSingularFixed32Field(value: &self.totalPackets) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.isPayloadEncrypted) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.version != 0 {
      try visitor.visitSingularInt32Field(value: self.version, fieldNumber: 1)
    }
    if self.operation != .unknown {
      try visitor.visitSingularEnumField(value: self.operation, fieldNumber: 2)
    }
    if self.packetNumber != 0 {
      try visitor.visitSingularFixed32Field(value: self.packetNumber, fieldNumber: 3)
    }
    if self.totalPackets != 0 {
      try visitor.visitSingularFixed32Field(value: self.totalPackets, fieldNumber: 4)
    }
    if self.isPayloadEncrypted != false {
      try visitor.visitSingularBoolField(value: self.isPayloadEncrypted, fieldNumber: 5)
    }
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Com_Google_Companionprotos_MessageV1, rhs: Com_Google_Companionprotos_MessageV1) -> Bool {
    if lhs.version != rhs.version {return false}
    if lhs.operation != rhs.operation {return false}
    if lhs.packetNumber != rhs.packetNumber {return false}
    if lhs.totalPackets != rhs.totalPackets {return false}
    if lhs.isPayloadEncrypted != rhs.isPayloadEncrypted {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
