// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: third_party/companion_protos/operation_type.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Com_Google_Companionprotos_OperationType: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unknown // = 0
  case encryptionHandshake // = 2
  case ack // = 3
  case clientMessage // = 4
  case query // = 5
  case queryResponse // = 6
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 2: self = .encryptionHandshake
    case 3: self = .ack
    case 4: self = .clientMessage
    case 5: self = .query
    case 6: self = .queryResponse
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .encryptionHandshake: return 2
    case .ack: return 3
    case .clientMessage: return 4
    case .query: return 5
    case .queryResponse: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Com_Google_Companionprotos_OperationType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Com_Google_Companionprotos_OperationType] = [
    .unknown,
    .encryptionHandshake,
    .ack,
    .clientMessage,
    .query,
    .queryResponse,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Com_Google_Companionprotos_OperationType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "OPERATION_TYPE_UNKNOWN"),
    2: .same(proto: "ENCRYPTION_HANDSHAKE"),
    3: .same(proto: "ACK"),
    4: .same(proto: "CLIENT_MESSAGE"),
    5: .same(proto: "QUERY"),
    6: .same(proto: "QUERY_RESPONSE"),
  ]
}
